In [1]:
 #NumPy vs Pandas 

import pandas as pd
import numpy as np

# -----------------------------
# Step 1: Creating some random Data 
# -----------------------------
data = {
    "Student": ["Ava", "Ben", "Cara"],
    "Exam1": [80, 70, 90],
    "Exam2": [85, 75, 95],
    "Exam3": [90, 80, 100]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print()

# -----------------------------
# Step 2: Pandas task (table logic)
# -----------------------------
# Pandas is great for simple column operations
df["Average"] = (df["Exam1"] + df["Exam2"] + df["Exam3"]) / 3

print("Added Average using pandas:")
print(df)
print()

# -----------------------------
# Step 3: NumPy task (where NumPy shines)
# -----------------------------
# Suppose each exam has a DIFFERENT weight:
# Exam1 = 20%, Exam2 = 30%, Exam3 = 50%

weights = np.array([0.2, 0.3, 0.5])

# Get just the numeric scores as a NumPy array
scores = df[["Exam1", "Exam2", "Exam3"]].to_numpy()

print("Scores array:")
print(scores)
print()

# Multiply each column by its weight (broadcasting!)
weighted_scores = scores * weights

print("After applying weights (NumPy broadcasting):")
print(weighted_scores)
print()

# Sum across each row to get weighted average
weighted_average = np.sum(weighted_scores, axis=1)
#np.sum(scores)          # axis=None everything, so if it's a 2D array it's one number
#np.sum(scores, axis=0)  # down columns
#np.sum(scores, axis=1)  # across rows


print("Final weighted averages:")
print(weighted_average)

Original DataFrame:
  Student  Exam1  Exam2  Exam3
0     Ava     80     85     90
1     Ben     70     75     80
2    Cara     90     95    100

Added Average using pandas:
  Student  Exam1  Exam2  Exam3  Average
0     Ava     80     85     90     85.0
1     Ben     70     75     80     75.0
2    Cara     90     95    100     95.0

Scores array:
[[ 80  85  90]
 [ 70  75  80]
 [ 90  95 100]]

After applying weights (NumPy broadcasting):
[[16.  25.5 45. ]
 [14.  22.5 40. ]
 [18.  28.5 50. ]]

Final weighted averages:
[86.5 76.5 96.5]


## Pandas and NumPy: 
For this in class lab you'll put together what we have been learning.  There are three different datasets so be sure you have them.  You don't always have to convert to NumPy arrays but if you are going broadcasting, then you should.

### **Part 1: Environmental Science - Air Quality Classification**

You are given a dataset containing air quality measurements from various locations. The dataset includes the following columns:
* Location (string): Name of the monitoring station
* Date (datetime): Date of the measurement
* PM2.5 (float): Particulate matter concentration (µg/m³)
* Temperature (float): Temperature at the time of measurement (°C)
* Humidity (float): Relative humidity (%)


**Do the following:**
1. Compute the average PM2.5 concentration for each location using NumPy.

2. Identify the day with the highest recorded PM2.5 concentration.

3. Create a new column AQI_Score using NumPy broadcasting assigning the following values as follows: 1 for PM2.5 < 50, 2 for 50 ≤ PM2.5 < 100, 3 for PM2.5 ≥ 100

4. Calculate the standard deviation of PM2.5 for each location using NumPy.

5.  Use a line plot to visualize PM2.5 levels over time for a specific location. To do this use matplotlib.plot.

In [22]:
# Read in data
import pandas as pd
import numpy as np

data=pd.read_csv("hw6_ environmental_science_data.csv")
#print(data.head())
# Grab the data you need and convert it to a Numpy array
np_air=data.to_numpy()


#1. Compute the average PM2.5 concentration for each location.

data.groupby("Location")["PM2.5"].mean()

#2. Identify the day with the highest recorded PM2.5 concentration.

id_max = data["PM2.5"].idxmax()
#print(id_max)

#print(data.iloc[id_max])
#print(data["PM2.5"].max())

#maxDF= data.iloc[id_max]
#print(maxDF["Location"])

print(data.iloc[id_max]["Date"])



#3. Create a new column AQI_Score using NumPy broadcasting assigning the following values as follows: 1 for PM2.5 < 50, 2 for 50 ≤ PM2.5 < 100, 3 for PM2.5 ≥ 100
#Be sure to print the resulting array

lev_1_mask=data["PM2.5"]<50
lev_2_mask=[data["PM2.5"]>=50 & (data["PM2.5"]<100)]

data["AQI_Score"]=0
#data.head()
data[lev_1_mask]["


# 4. Calculate the standard deviation of PM2.5 for each location using NumPy.

# 5. Use a line plot to visualize PM2.5 levels over time for a specific location. To do this use matplotlib.plot.

2023-03-16


,Location,Date,PM2.5,Temperature (C),Humidity (%),AQI_Score
0,Station1,2023-01-01,165.635739,21.595667,35.777257,0
1,Station4,2023-01-02,111.816097,33.065575,35.992695,0
2,Station3,2023-01-03,86.237963,3.044535,49.537256,0
3,Station2,2023-01-04,166.226254,5.534390,37.644870,0
4,Station2,2023-01-05,35.090778,14.659294,57.567466,0




### **Part 2: Finance - Stock Price Trends**
You are given a dataset of stock prices for a company over 30 days:
*`Date` (datetime): Date of the stock value
* `Close` (float): Closing stock price

**Do the following:**
1. Compute the daily percentage change in closing price using NumPy (no pandas `.pct_change()`).
2. Find the highest and lowest closing price along with the date they occurred.
3. Use NumPy broadcasting to create a column `AboveAverage`:
   - `True` if the closing price is above the mean closing price, `False` otherwise.
4. Calculate the **standard deviation** and **mean** of the closing prices using NumPy.
5. Create a new column `ZScore` for the closing price:
  $  Z = \frac{x - \text{mean}}{\text{std}} $

7. Create a column `HighVolatility`:
   - `True` if the absolute Z-score is greater than 1.
8. Use NumPy to calculate **cumulative return** from the first day:
  $  R_t = \frac{P_t - P_0}{P_0} $
9. Use a line plot to visualize closing price and cumulative return.








In [ ]:
# Set you code up here



#1. Compute the daily percentage change in closing price using NumPy (no pandas `.pct_change()`).


#2. Find the highest and lowest closing price along with the date they occurred.

#3. Use NumPy broadcasting to create a column `AboveAverage`:
   #`True` if the closing price is above the mean closing price, `False` otherwise.


#4. Calculate the standard deviation and mean of the closing prices using NumPy.




#5. Create a new column `ZScore` for the closing price:

#6. Create a column `HighVolatility`


#7. Use NumPy to calculate **cumulative return** from the first day:
 
#8. Use a line plot to visualize closing price and cumulative return.




### **Part 3: Social Media Data Analysis**
You are analyzing engagement data from social media posts. The dataset includes:
- `Timestamp` (datetime): When the post was made
- `Likes`, `Shares`, `Comments` (int): Count of user interactions
- `UserFollowers` (int): Number of followers the user had at posting time

**Do the following:**
1. Create a column `Engagement` that sums likes, shares, and comments using NumPy broadcasting.
2. Compute `EngagementPerFollower` by dividing `Engagement` by `UserFollowers` using broadcasting.
3. Create a `Viral` column where:
   - Value is `True` if `EngagementPerFollower > 0.1`, else `False`
4. Display the top 5 viral posts by engagement.
5. Create a scatter plot of `UserFollowers` vs `Engagement`.
6. Compute the standard deviation of `EngagementPerFollower` using NumPy.


In [ ]:
#1. Create a column `Engagement` that sums likes, shares, and comments using NumPy broadcasting.

#2. Compute `EngagementPerFollower` by dividing `Engagement` by `UserFollowers` using broadcasting.

#3. Create a `Viral` column where:
#   - Value is `True` if `EngagementPerFollower > 0.1`, else `False`

#4. Display the top 5 viral posts by engagement.

#5. Create a scatter plot of `UserFollowers` vs `Engagement`.  Google how to do this:)  

#6. Compute the standard deviation of `EngagementPerFollower` using NumPy.